# Generated by Django 3.1.5 on 2025-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('indent_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('specifications', models.TextField()),
                ('approval_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('NOT_APPROVED', 'NOT_APPROVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('Consumable', 'Consumable'), ('Non-Consumable', 'Non-Consumable')], max_length=20)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SectionInfo',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
