# Generated by Django 3.1.5 on 2025-03-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('approval_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('NOT_APPROVED', 'NOT_APPROVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='inventory.departmentinfo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='inventory.item')),
            ],
        ),
    ]
