# Generated by Django 3.1.5 on 2025-03-24 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='department',
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
