# Generated by Django 3.1.5 on 2025-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_new_fields'),  # keep this if it's your last successful migration
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approval_status', models.CharField(
                    choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')],
                    default='PENDING',
                    max_length=20
                )),
            ],
            options={
                'verbose_name': 'Returned Item',
                'verbose_name_plural': 'Returned Items',
                'ordering': ['-return_date'],
            },
        ),
    ]
