# Generated by Django 3.1.5 on 2025-03-24 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20250324_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryrequest',
            old_name='name',
            new_name='department_name',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='item',
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='item_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
