# Generated by Django 3.1.5 on 2025-03-24 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20250324_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='purpose',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='specifications',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
