# Generated by Django 3.1.5 on 2025-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleaccess',
            name='inventory_management',
            field=models.BooleanField(default=False),
        ),
    ]
