# Generated by Django 3.1.5 on 2025-04-21 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_procedures', '0002_auto_20250408_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 4, 21)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='interview_date',
            field=models.DateField(default=datetime.date(2025, 4, 21)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 4, 21)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='test_date',
            field=models.DateField(default=datetime.date(2025, 4, 21)),
        ),
    ]
